

services:

  web:
    build: .
    container_name: qchicharron_app
    command: daphne -b 0.0.0.0 -p 8000 configuracion.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=configuracion.settings
    volumes:
      - .:/app
    ports:
      - "8015:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis  # ðŸ‘ˆ agregar dependencia

  db:
    image: mysql:8.0
    container_name: qchicharron_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:  # ðŸ‘ˆ servicio nuevo
    image: redis:7-alpine
    container_name: qchicharron_redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: qchicharron_phpmyadmin
    restart: always
    ports:
      - "8030:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  mysql_data:

